### ISSUE TITLE
Parsing issue - ruby tag

### ISSUE THREAD

**Issue by christriants** [asticode/go-astisub#126]
There seems to be an issue when converting a VTT file containing a ruby tag.

Steps to replicate:
1) Save the following VTT file (new_file.vtt):
```
WEBVTT

1
00:00:00.100 --> 00:00:06.032
<ruby>静<rt>しず</rt></ruby>
```

2) Run `go-astisub % astisub convert -i <new_file.vtt> -o <new_file_converted.vtt>`

3) Observe the new VTT file has a an additional `ruby` tag:
```
WEBVTT

1
00:00:00.100 --> 00:00:06.032
<ruby>静</ruby> <ruby><rt>しず</rt></ruby>
```

This leads to incorrect markup when applied to the DOM.

<img width="151" alt="Image" src="https://github.com/user-attachments/assets/b154e632-1bd8-4e91-ab6d-79d3d9cb2110" />

**Comment by asticode** [comment]
Thanks for the report 👍 

I've pushed a fix on `master` and tag `v0.32.1`, could you confirm this resolves your issue?

**Comment by christriants** [comment]
Hi, @asticode! Thanks for your change. I appreciate that you're working on a fix!

After pulling the latest changes and running the same command from step 2, I am still seeing the issue-output from step 3:
```
WEBVTT

1
00:00:00.100 --> 00:00:06.032
<ruby>静</ruby> <ruby><rt>しず</rt></ruby>
```

Are you seeing a different output?

**Comment by christriants** [comment]
Oh. Actually, I might have been incorrect. I am now seeing:
```
WEBVTT

1
00:00:00.100 --> 00:00:06.032
<ruby>静 <rt>しず</rt></ruby>
```

This seems like a fix! The only nitpick I have is that there seems to be a space here: `<ruby>静 <rt>`. 

Awesome, thank you!

**Comment by asticode** [comment]
Is the space a problem in your case?

**Comment by christriants** [comment]
This shouldn't be an issue. Thanks for the fix.
